# Generated by Django 4.1.3 on 2022-11-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='producto', max_length=40)),
                ('descripcion', models.TextField(default='descripcion')),
                ('precio', models.FloatField(default=0)),
                ('imagen', models.ImageField(default=None, upload_to='')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.producto')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('myapp.producto',),
        ),
        migrations.CreateModel(
            name='Ordenador',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.producto')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('myapp.producto',),
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.producto')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('myapp.producto',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=60)),
                ('contrasenya', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('productos_guardados', models.ManyToManyField(to='myapp.producto')),
            ],
        ),
    ]
