# Generated by Django 4.1.3 on 2022-11-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_audio_diametrowoofer_audio_numerowoofer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenador',
            name='procesador',
        ),
        migrations.AddField(
            model_name='ordenador',
            name='proces',
            field=models.CharField(default='Intel', max_length=100),
        ),
    ]
