# Generated by Django 4.1.3 on 2022-11-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_audio_diametrowoofer_audio_numerowoofer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='productos_guardados',
            field=models.ManyToManyField(blank=True, to='myapp.producto'),
        ),
    ]
