# Generated by Django 4.1.3 on 2022-11-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_cliente_productos_guardados'),
        ('myapp', '0003_remove_cliente_fecha_nacimiento'),
    ]

    operations = [
    ]
