# Generated by Django 4.1.3 on 2022-11-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_20221123_1456'),
        ('myapp', '0004_remove_ordenador_microfono_ordenador_sistemadeaudio'),
    ]

    operations = [
    ]
