# Generated by Django 4.1.3 on 2022-11-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_20221123_2235'),
        ('myapp', '0005_merge_20221123_1713'),
    ]

    operations = [
    ]
