# Generated by Django 4.1.3 on 2022-12-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_merge_20221124_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagen1',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
