# Generated by Django 4.1.3 on 2022-12-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_imagen_producto_imagen1_producto_imagen2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen1',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen3',
        ),
    ]
